import type { Metadata } from "next";
import "../globals.css";
import { geistSans, geistMono } from "@/app/layout";
import HomeNavBar from "../components/homeNavBar";


const metadata: Metadata = {
  title: "Page",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HomeNavBar />
        {children}
      </body>
    </html>
  );
}